# Generated by Django 5.2.8 on 2025-11-15 19:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('linea', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='rutas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='rutas.punto')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='rutas.punto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
        ),
    ]
